# Translations template for barbican.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the barbican project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: barbican 1.0.0.dev98.g4d3f206\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-09-24 21:15+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: barbican/api/__init__.py:56
msgid "Read Error"
msgstr ""

#: barbican/api/__init__.py:66
msgid "Malformed JSON"
msgstr ""

#: barbican/api/__init__.py:100
msgid ""
"{operation} attempt not allowed - please review your user/project "
"privileges"
msgstr ""

#: barbican/api/__init__.py:110
msgid "{operation} failure seen - please contact site administrator."
msgstr ""

#: barbican/api/__init__.py:114
msgid "{operation} issue seen - {reason}."
msgstr ""

#: barbican/api/controllers/__init__.py:97
msgid "System"
msgstr ""

#: barbican/api/controllers/__init__.py:129
msgid "Unexpected content type: {type}. Expected content types are: {expected}"
msgstr ""

#: barbican/api/controllers/acls.py:65
msgid "SecretACL(s) retrieval"
msgstr ""

#: barbican/api/controllers/acls.py:74 barbican/api/controllers/acls.py:126
msgid "SecretACL(s) Update"
msgstr ""

#: barbican/api/controllers/acls.py:189
msgid "SecretACL(s) deletion"
msgstr ""

#: barbican/api/controllers/acls.py:230
msgid "ContainerACL(s) retrieval"
msgstr ""

#: barbican/api/controllers/acls.py:239 barbican/api/controllers/acls.py:292
msgid "ContainerACL(s) Update"
msgstr ""

#: barbican/api/controllers/acls.py:358
msgid "ContainerACL(s) deletion"
msgstr ""

#: barbican/api/controllers/cas.py:35
msgid "Not Found. CA not found."
msgstr ""

#: barbican/api/controllers/cas.py:40
msgid "Not Found. CA attribute not found."
msgstr ""

#: barbican/api/controllers/cas.py:45
msgid "Not Found. CA not in project."
msgstr ""

#: barbican/api/controllers/cas.py:52
msgid "Cannot set CA as a preferred CA as it is not a project CA."
msgstr ""

#: barbican/api/controllers/cas.py:59
msgid ""
"Please change the preferred CA to a different project CA before removing "
"it."
msgstr ""

#: barbican/api/controllers/cas.py:95
msgid "Certificate Authority retrieval"
msgstr ""

#: barbican/api/controllers/cas.py:103
msgid "CA Signing Cert retrieval"
msgstr ""

#: barbican/api/controllers/cas.py:111
msgid "CA Cert Chain retrieval"
msgstr ""

#: barbican/api/controllers/cas.py:119
msgid "CA projects retrieval"
msgstr ""

#: barbican/api/controllers/cas.py:137
msgid "Add CA to project"
msgstr ""

#: barbican/api/controllers/cas.py:166
msgid "Remove CA from project"
msgstr ""

#: barbican/api/controllers/cas.py:211
msgid "Set preferred project CA"
msgstr ""

#: barbican/api/controllers/cas.py:235
msgid "Set global preferred CA"
msgstr ""

#: barbican/api/controllers/cas.py:248
msgid "CA deletion"
msgstr ""

#: barbican/api/controllers/cas.py:296
msgid "Certificate Authorities retrieval (limited)"
msgstr ""

#: barbican/api/controllers/cas.py:332
msgid "Certificate Authorities retrieval"
msgstr ""

#: barbican/api/controllers/cas.py:409
msgid "Retrieve global preferred CA"
msgstr ""

#: barbican/api/controllers/cas.py:417
msgid "No global preferred CA defined"
msgstr ""

#: barbican/api/controllers/cas.py:426
msgid "Unset global preferred CA"
msgstr ""

#: barbican/api/controllers/cas.py:443
msgid "Retrieve project preferred CA"
msgstr ""

#: barbican/api/controllers/cas.py:452
msgid "No preferred CA defined for this project"
msgstr ""

#: barbican/api/controllers/cas.py:460
msgid "CA creation"
msgstr ""

#: barbican/api/controllers/consumers.py:32
msgid "Not Found. Sorry but your consumer is in another castle."
msgstr ""

#: barbican/api/controllers/consumers.py:49
msgid "ContainerConsumer retrieval"
msgstr ""

#: barbican/api/controllers/consumers.py:89
msgid "ContainerConsumers(s) retrieval"
msgstr ""

#: barbican/api/controllers/consumers.py:130
msgid "ContainerConsumer creation"
msgstr ""

#: barbican/api/controllers/consumers.py:163
msgid "ContainerConsumer deletion"
msgstr ""

#: barbican/api/controllers/containers.py:36
msgid "Not Found. Sorry but your container is in another castle."
msgstr ""

#: barbican/api/controllers/containers.py:64
msgid "Container retrieval"
msgstr ""

#: barbican/api/controllers/containers.py:80
msgid "Container deletion"
msgstr ""

#: barbican/api/controllers/containers.py:132
msgid "Containers(s) retrieval"
msgstr ""

#: barbican/api/controllers/containers.py:172
msgid "Container creation"
msgstr ""

#: barbican/api/controllers/containers.py:202
msgid "Secret provided for '{secret_name}' doesn't exist."
msgstr ""

#: barbican/api/controllers/orders.py:32
msgid "Not Found. Sorry but your order is in another castle."
msgstr ""

#: barbican/api/controllers/orders.py:38
msgid "Secret metadata expected but not received."
msgstr ""

#: barbican/api/controllers/orders.py:43
msgid "Order update is not supported."
msgstr ""

#: barbican/api/controllers/orders.py:48
msgid "Updates are not supported for order type {0}."
msgstr ""

#: barbican/api/controllers/orders.py:54
msgid "Only PENDING orders can be updated. Order is in the{0} state."
msgstr ""

#: barbican/api/controllers/orders.py:60
msgid "Cannot modify order type."
msgstr ""

#: barbican/api/controllers/orders.py:78
msgid "Order retrieval"
msgstr ""

#: barbican/api/controllers/orders.py:84 barbican/api/controllers/orders.py:189
msgid "Order update"
msgstr ""

#: barbican/api/controllers/orders.py:120
msgid "Order deletion"
msgstr ""

#: barbican/api/controllers/orders.py:161
msgid "Order(s) retrieval"
msgstr ""

#: barbican/api/controllers/orders.py:195
msgid "Order creation"
msgstr ""

#: barbican/api/controllers/quotas.py:32
msgid "Not Found. Sorry but your project quotas are in another castle."
msgstr ""

#: barbican/api/controllers/quotas.py:48
msgid "Quotas"
msgstr ""

#: barbican/api/controllers/quotas.py:72 barbican/api/controllers/quotas.py:83
#: barbican/api/controllers/quotas.py:98 barbican/api/controllers/quotas.py:128
msgid "Project Quotas"
msgstr ""

#: barbican/api/controllers/secrets.py:37
msgid "Not Found. Sorry but your secret is in another castle."
msgstr ""

#: barbican/api/controllers/secrets.py:43
msgid "Secret already has data, cannot modify it."
msgstr ""

#: barbican/api/controllers/secrets.py:52
msgid ""
"Transport key wrapped session key has been provided to wrap secrets for "
"retrieval, but the transport key id has not been provided."
msgstr ""

#: barbican/api/controllers/secrets.py:84
msgid "Secret retrieval"
msgstr ""

#: barbican/api/controllers/secrets.py:160
msgid "Secret payload retrieval"
msgstr ""

#: barbican/api/controllers/secrets.py:177
msgid "Secret update"
msgstr ""

#: barbican/api/controllers/secrets.py:186
msgid "Content-Type of '{content_type}' is not supported for PUT."
msgstr ""

#: barbican/api/controllers/secrets.py:216
msgid "Secret deletion"
msgstr ""

#: barbican/api/controllers/secrets.py:252
msgid "Secret(s) retrieval"
msgstr ""

#: barbican/api/controllers/secrets.py:312
msgid "Secret creation"
msgstr ""

#: barbican/api/controllers/transportkeys.py:33
msgid "Not Found. Transport Key not found."
msgstr ""

#: barbican/api/controllers/transportkeys.py:49
msgid "Transport Key retrieval"
msgstr ""

#: barbican/api/controllers/transportkeys.py:61
msgid "Transport Key deletion"
msgstr ""

#: barbican/api/controllers/transportkeys.py:93
msgid "Transport Key(s) retrieval"
msgstr ""

#: barbican/api/controllers/transportkeys.py:131
msgid "Transport Key Creation"
msgstr ""

#: barbican/api/controllers/versions.py:38
msgid "The version you requested wasn't found"
msgstr ""

#: barbican/api/controllers/versions.py:105
msgid "Version retrieval"
msgstr ""

#: barbican/api/middleware/context.py:122
msgid "Missing X-Project-Id"
msgstr ""

#: barbican/common/config.py:36
msgid "Role used to identify an authenticated user as administrator."
msgstr ""

#: barbican/common/config.py:39
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""

#: barbican/common/config.py:75
msgid "Seconds (float) to wait before starting retry scheduler"
msgstr ""

#: barbican/common/config.py:78
msgid "Seconds (float) to wait between periodic schedule events"
msgstr ""

#: barbican/common/config.py:86
msgid "True enables queuing, False invokes workers synchronously"
msgstr ""

#: barbican/common/config.py:89
msgid "Queue namespace"
msgstr ""

#: barbican/common/config.py:91
msgid "Queue topic name"
msgstr ""

#: barbican/common/config.py:93
msgid "Version of tasks invoked via queue"
msgstr ""

#: barbican/common/config.py:95
msgid "Server name for RPC task processing server"
msgstr ""

#: barbican/common/config.py:103
msgid "True enables keystone notification listener  functionality."
msgstr ""

#: barbican/common/config.py:106
msgid ""
"The default exchange under which topics are scoped. May be overridden by "
"an exchange name specified in the transport_url option."
msgstr ""

#: barbican/common/config.py:110
msgid ""
"Keystone notification queue topic name. This name needs to match one of "
"values mentioned in Keystone deployment's 'notification_topics' "
"configuration e.g.    notification_topics=notifications,     "
"barbican_notificationsMultiple servers may listen on a topic and messages"
" will be dispatched to one of the servers in a round-robin fashion. "
"That's why Barbican service should have its own dedicated notification "
"queue so that it receives all of Keystone notifications."
msgstr ""

#: barbican/common/config.py:122
msgid ""
"True enables requeue feature in case of notification processing error. "
"Enable this only when underlying transport supports this feature."
msgstr ""

#: barbican/common/config.py:126
msgid "Version of tasks invoked via notifications"
msgstr ""

#: barbican/common/config.py:128
msgid ""
"Define the number of max threads to be used for notification server "
"processing functionality."
msgstr ""

#: barbican/common/exception.py:32
msgid "An unknown exception occurred"
msgstr ""

#: barbican/common/exception.py:60
msgid "failure seen - please contact site administrator."
msgstr ""

#: barbican/common/exception.py:79
msgid "Missing required argument."
msgstr ""

#: barbican/common/exception.py:83
#, python-format
msgid "Missing required credential: %(required)s"
msgstr ""

#: barbican/common/exception.py:87
#, python-format
msgid "Missing required metadata field for %(required)s"
msgstr ""

#: barbican/common/exception.py:93
#, python-format
msgid "Invalid subject DN: %(subject_dn)s"
msgstr ""

#: barbican/common/exception.py:99
#, python-format
msgid "Invalid container: %(reason)s"
msgstr ""

#: barbican/common/exception.py:105
msgid "Invalid extensions data."
msgstr ""

#: barbican/common/exception.py:111
msgid "Invalid CMC Data"
msgstr ""

#: barbican/common/exception.py:117
#, python-format
msgid "Invalid PKCS10 Data: %(reason)s"
msgstr ""

#: barbican/common/exception.py:123
msgid "Invalid Certificate Request Type"
msgstr ""

#: barbican/common/exception.py:129
msgid "Extensions are not yet supported.  Specify a valid profile instead."
msgstr ""

#: barbican/common/exception.py:136
msgid "Full CMC Requests are not yet supported."
msgstr ""

#: barbican/common/exception.py:142
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""

#: barbican/common/exception.py:147
msgid "An object with the specified identifier was not found."
msgstr ""

#: barbican/common/exception.py:151
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr ""

#: barbican/common/exception.py:155
msgid "The Store URI was malformed."
msgstr ""

#: barbican/common/exception.py:159
msgid "An object with the same identifier already exists."
msgstr ""

#: barbican/common/exception.py:163
msgid "There is not enough disk space on the image storage media."
msgstr ""

#: barbican/common/exception.py:167
msgid "Permission to write image storage media denied."
msgstr ""

#: barbican/common/exception.py:171
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""

#: barbican/common/exception.py:175
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr ""

#: barbican/common/exception.py:179
msgid "Authorization failed."
msgstr ""

#: barbican/common/exception.py:183
msgid "You are not authenticated."
msgstr ""

#: barbican/common/exception.py:187 barbican/common/exception.py:195
#: barbican/common/exception.py:204
msgid "You are not authorized to complete this action."
msgstr ""

#: barbican/common/exception.py:191
msgid "Operation is not supported."
msgstr ""

#: barbican/common/exception.py:199
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr ""

#: barbican/common/exception.py:208
msgid "Data supplied was not valid."
msgstr ""

#: barbican/common/exception.py:212
msgid "No data supplied to process."
msgstr ""

#: barbican/common/exception.py:218
msgid "Sort key supplied was not valid."
msgstr ""

#: barbican/common/exception.py:222
msgid "Unable to filter using the specified range."
msgstr ""

#: barbican/common/exception.py:226
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr ""

#: barbican/common/exception.py:230
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr ""

#: barbican/common/exception.py:234
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr ""

#: barbican/common/exception.py:238
msgid "There was an error migrating the database."
msgstr ""

#: barbican/common/exception.py:242
msgid "There was an error connecting to a server"
msgstr ""

#: barbican/common/exception.py:246
msgid "There was an error configuring the client."
msgstr ""

#: barbican/common/exception.py:250
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""

#: barbican/common/exception.py:257
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: barbican/common/exception.py:260
msgid "Provided information too large to process"
msgstr ""

#: barbican/common/exception.py:270
msgid ""
"The request returned 503 Service Unavilable. This generally occurs on "
"service overload or other transient outage."
msgstr ""

#: barbican/common/exception.py:281
msgid "The request returned 500 Internal Server Error."
msgstr ""

#: barbican/common/exception.py:285
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: barbican/common/exception.py:290
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr ""

#: barbican/common/exception.py:294
#, python-format
msgid "Invalid content encoding %(content_encoding)s"
msgstr ""

#: barbican/common/exception.py:298
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr ""

#: barbican/common/exception.py:303
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""

#: barbican/common/exception.py:308
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""

#: barbican/common/exception.py:313
msgid "Deleting images from this store is not supported."
msgstr ""

#: barbican/common/exception.py:317
msgid "Configuration for store failed. Adding images to this store is disabled."
msgstr ""

#: barbican/common/exception.py:322
#, python-format
msgid "'%(strategy)s' is not an available notifier strategy."
msgstr ""

#: barbican/common/exception.py:326
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr ""

#: barbican/common/exception.py:330
msgid "Received invalid HTTP redirect."
msgstr ""

#: barbican/common/exception.py:334
msgid "Response from Keystone does not contain a Barbican endpoint."
msgstr ""

#: barbican/common/exception.py:339
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""

#: barbican/common/exception.py:345
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr ""

#: barbican/common/exception.py:349
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr ""

#: barbican/common/exception.py:357
msgid "Failed to validate JSON information: "
msgstr ""

#: barbican/common/exception.py:358
msgid ""
"Provided object does not match schema '{schema}': {reason}. Invalid "
"property: '{property}'"
msgstr ""

#: barbican/common/exception.py:368
msgid "Error while attempting to decode payload."
msgstr ""

#: barbican/common/exception.py:369
msgid "Unable to decode request data."
msgstr ""

#: barbican/common/exception.py:373
#, python-format
msgid ""
"No support for value set on field '%(field)s' on schema '%(schema)s': "
"%(reason)s"
msgstr ""

#: barbican/common/exception.py:375
msgid "Provided field value is not supported"
msgstr ""

#: barbican/common/exception.py:384
#, python-format
msgid ""
"Feature not implemented for value set on field '%(field)s' on schema "
"'%(schema)s': %(reason)s"
msgstr ""

#: barbican/common/exception.py:393
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr ""

#: barbican/common/exception.py:397
msgid ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Barbican."
msgstr ""

#: barbican/common/exception.py:402
msgid "The provided image is too large."
msgstr ""

#: barbican/common/exception.py:406
#, python-format
msgid ""
"Container %(container_id)s does not exist for stored key certificate "
"generation."
msgstr ""

#: barbican/common/exception.py:411
#, python-format
msgid ""
"Container %(container_id)s does not reference a private key needed for "
"stored key certificate generation."
msgstr ""

#: barbican/common/exception.py:416
#, python-format
msgid "The provided UUID in the URI (%(uuid_string)s) is malformed."
msgstr ""

#: barbican/common/exception.py:418
msgid "The provided UUID in the URI is malformed."
msgstr ""

#: barbican/common/exception.py:423
#, python-format
msgid "Invalid CA_ID: %(ca_id)s"
msgstr ""

#: barbican/common/exception.py:424
msgid "The ca_id provided in the request is invalid"
msgstr ""

#: barbican/common/exception.py:429
#, python-format
msgid "CA specified by ca_id %(ca_id)s not defined for project: %(project_id)s"
msgstr ""

#: barbican/common/exception.py:431
msgid "The ca_id provided in the request is not defined for this project"
msgstr ""

#: barbican/common/exception.py:437
#, python-format
msgid ""
"Quota reached for project %(external_project_id)s. Only %(quota)s "
"%(resource_type)s are allowed."
msgstr ""

#: barbican/common/exception.py:439
msgid "Creation not allowed because a quota has been reached"
msgstr ""

#: barbican/common/exception.py:451
#, python-format
msgid "Invalid Parent CA: %(parent_ca_ref)s"
msgstr ""

#: barbican/common/exception.py:457
msgid "Plugin does not support generation of subordinate CAs"
msgstr ""

#: barbican/common/exception.py:463
msgid "Errors in creating subordinate CA: %(name)"
msgstr ""

#: barbican/common/exception.py:468
msgid "Only subordinate CAs can be deleted."
msgstr ""

#: barbican/common/exception.py:473
msgid "Subordinate CA is not owned by this project"
msgstr ""

#: barbican/common/utils.py:134
msgid "Cannot generate a fullname for a null instance"
msgstr ""

#: barbican/common/validators.py:94
msgid "Bad Container Reference {ref}"
msgstr ""

#: barbican/common/validators.py:104
msgid "Container Not Found"
msgstr ""

#: barbican/common/validators.py:108
msgid "Container Wrong Type"
msgstr ""

#: barbican/common/validators.py:144
msgid "{schema_name}' within '{parent_schema_name}"
msgstr ""

#: barbican/common/validators.py:238
msgid "If 'payload' specified, must be non empty"
msgstr ""

#: barbican/common/validators.py:246
msgid "payload must be provided when payload_content_type is specified"
msgstr ""

#: barbican/common/validators.py:254
msgid "payload_content_type is not one of {supported}"
msgstr ""

#: barbican/common/validators.py:280 barbican/common/validators.py:585
msgid "Invalid date for 'expiration'"
msgstr ""

#: barbican/common/validators.py:294
msgid "'expiration' is before current time"
msgstr ""

#: barbican/common/validators.py:307
msgid "If 'payload' is supplied, 'payload_content_type' must also be supplied."
msgstr ""

#: barbican/common/validators.py:314
msgid "payload_content_type {supplied} is not one of {supported}"
msgstr ""

#: barbican/common/validators.py:324
msgid "payload_content_encoding is not one of {supported}"
msgstr ""

#: barbican/common/validators.py:337
msgid "Invalid payload for payload_content_encoding"
msgstr ""

#: barbican/common/validators.py:420
msgid "'payload' not allowed for key type order"
msgstr ""

#: barbican/common/validators.py:437
msgid "'payload' not allowed for asymmetric type order"
msgstr ""

#: barbican/common/validators.py:454
msgid "'payload' not allowed for certificate type order"
msgstr ""

#: barbican/common/validators.py:528
msgid "Bad format"
msgstr ""

#: barbican/common/validators.py:535
msgid "Signing key incorrect"
msgstr ""

#: barbican/common/validators.py:568
msgid "'algorithm' is required field for {0} type order"
msgstr ""

#: barbican/common/validators.py:597
msgid "Must have non-zero positive bit_length to generate secret"
msgstr ""

#: barbican/common/validators.py:605
msgid "Must be a positive integer that is a multiple of 8"
msgstr ""

#: barbican/common/validators.py:613
msgid "Feature not implemented for '{0}' order type"
msgstr ""

#: barbican/common/validators.py:722
msgid "Duplicate reference names are not allowed"
msgstr ""

#: barbican/common/validators.py:734
msgid "Duplicate secret ids are not allowed"
msgstr ""

#: barbican/common/validators.py:745
msgid "Secret_ref does not match the configured hostname, please try again"
msgstr ""

#: barbican/common/validators.py:766
msgid ""
"only 'private_key', 'public_key' and 'private_key_passphrase' reference "
"names are allowed for RSA type"
msgstr ""

#: barbican/common/validators.py:774
msgid ""
"The minimum required reference names are 'public_key' and'private_key' "
"for RSA type"
msgstr ""

#: barbican/common/validators.py:787
msgid ""
"only 'private_key', 'certificate' , 'private_key_passphrase',  or "
"'intermediates' reference names are allowed for Certificate type"
msgstr ""

#: barbican/common/validators.py:795
msgid "The minimum required reference name is 'certificate' for Certificate type"
msgstr ""

#: barbican/common/validators.py:841
msgid "plugin_name must be provided"
msgstr ""

#: barbican/common/validators.py:848
msgid "transport_key must be provided"
msgstr ""

#: barbican/model/models.py:366
msgid "Must supply non-None {0} argument for SecretStoreMetadatum entry."
msgstr ""

#: barbican/model/models.py:587
msgid "Must supply non-None {0} argument for OrderPluginMetadatum entry."
msgstr ""

#: barbican/model/models.py:623
msgid "Must supply non-None {0} argument for OrderBarbicanMetadatum entry."
msgstr ""

#: barbican/model/models.py:798
msgid "Must supply non-None {0} argument for TransportKey entry."
msgstr ""

#: barbican/model/models.py:845
msgid "Must supply Non-None {0} argument for CertificateAuthority entry."
msgstr ""

#: barbican/model/models.py:919
msgid "Must supply non-None {0} argument for CertificateAuthorityMetadatum entry."
msgstr ""

#: barbican/model/models.py:966
msgid "Must supply non-None {0} argument for ProjectCertificateAuthority entry."
msgstr ""

#: barbican/model/models.py:1018
msgid "Must supply non-None {0} argument for PreferredCertificateAuthority entry."
msgstr ""

#: barbican/model/models.py:1073
msgid "Must supply non-None {0} argument for SecretACL entry."
msgstr ""

#: barbican/model/models.py:1149
msgid "Must supply non-None {0} argument for ContainerACL entry."
msgstr ""

#: barbican/model/models.py:1213
msgid "Must supply non-None {0} argument for SecretACLUser entry."
msgstr ""

#: barbican/model/models.py:1250
msgid "Must supply non-None {0} argument for ContainerACLUser entry."
msgstr ""

#: barbican/model/models.py:1297
msgid "Must supply non-None {0} argument for ProjectQuotas entry."
msgstr ""

#: barbican/model/repositories.py:161
msgid "No SQL connection configured"
msgstr ""

#: barbican/model/repositories.py:182
msgid ""
"Error configuring registry database with supplied sql_connection. Got "
"error: {error}"
msgstr ""

#: barbican/model/repositories.py:362
msgid "Must supply non-None {entity_name}."
msgstr ""

#: barbican/model/repositories.py:368
msgid "Must supply {entity_name} with id=None (i.e. new entity)."
msgstr ""

#: barbican/model/repositories.py:446
msgid "{entity_name} status is required."
msgstr ""

#: barbican/model/repositories.py:451
msgid "Invalid status '{status}' for {entity_name}."
msgstr ""

#: barbican/model/repositories.py:471
msgid "{entity_name} is missing query build method for get project entities."
msgstr ""

#: barbican/model/repositories.py:541
#, python-format
msgid "Error deleting project entities for project_id=%s"
msgstr ""

#: barbican/model/repositories.py:577
msgid "No {entity_name} found with keystone-ID {id}"
msgstr ""

#: barbican/model/repositories.py:708
msgid "No secret found with secret-ID {id}"
msgstr ""

#: barbican/model/repositories.py:800
msgid "Tried to register crypto plugin with null or empty name."
msgstr ""

#: barbican/model/repositories.py:1182
msgid "No container found with container-ID {id}"
msgstr ""

#: barbican/model/repositories.py:1259
msgid "Could not find {entity_name}"
msgstr ""

#: barbican/model/repositories.py:2176
msgid "No {entity} found with ID {id}"
msgstr ""

#: barbican/model/repositories.py:2182
msgid "Entity ID {entity_id} not found"
msgstr ""

#: barbican/model/repositories.py:2188
msgid "No entities of type {entity_name} found"
msgstr ""

#: barbican/model/repositories.py:2194
msgid "Entity '{entity_name}' already exists"
msgstr ""

#: barbican/plugin/dogtag.py:47
msgid "Path to PEM file for authentication"
msgstr ""

#: barbican/plugin/dogtag.py:50
msgid "Hostname for the Dogtag instance"
msgstr ""

#: barbican/plugin/dogtag.py:53
msgid "Port for the Dogtag instance"
msgstr ""

#: barbican/plugin/dogtag.py:55
msgid "Path to the NSS certificate database"
msgstr ""

#: barbican/plugin/dogtag.py:57
msgid "Password for the NSS certificate databases"
msgstr ""

#: barbican/plugin/dogtag.py:59
msgid "Profile for simple CMC requests"
msgstr ""

#: barbican/plugin/dogtag.py:62
msgid "List of automatically approved enrollment profiles"
msgstr ""

#: barbican/plugin/dogtag.py:107
msgid "nss_password is required"
msgstr ""

#: barbican/plugin/dogtag.py:133
msgid "pem_path is required"
msgstr ""

#: barbican/plugin/dogtag.py:147
msgid "Invalid algorithm passed in"
msgstr ""

#: barbican/plugin/dogtag.py:151
msgid "Operation not supported by Dogtag Plugin"
msgstr ""

#: barbican/plugin/dogtag.py:399
msgid ""
"Passphrase encryption is not supported for symmetric key generating "
"algorithms."
msgstr ""

#: barbican/plugin/dogtag.py:443
msgid "Passphrase encryption is not supported for DSA algorithm"
msgstr ""

#: barbican/plugin/dogtag.py:574
msgid ""
"DSA keys should not have a passphrase in the database, for being used "
"during retrieval."
msgstr ""

#: barbican/plugin/dogtag.py:578
msgid ""
"Secrets of type {secret_type} should not have a passphrase in the "
"database, for being used during retrieval."
msgstr ""

#: barbican/plugin/dogtag.py:596
msgid ""
"Encryption using session key is not supported when retrieving a "
"{secret_type} key."
msgstr ""

#: barbican/plugin/dogtag.py:625
msgid "Exception thrown by enroll_cert: {message}"
msgstr ""

#: barbican/plugin/dogtag.py:651
msgid "{request} not found for {operation} for order_id {order_id}"
msgstr ""

#: barbican/plugin/dogtag.py:703
msgid "No request found for request_id {request_id} for order {order_id}"
msgstr ""

#: barbican/plugin/dogtag.py:729
msgid ""
"Request {request_id} reports status_complete, but no cert_id has been "
"returned"
msgstr ""

#: barbican/plugin/dogtag.py:740
msgid "Certificate not found for cert_id: {cert_id}"
msgstr ""

#: barbican/plugin/dogtag.py:750
msgid "Invalid request_status returned by CA"
msgstr ""

#: barbican/plugin/dogtag.py:783 barbican/plugin/dogtag.py:828
#, python-format
msgid "Dogtag plugin does not support %s request type"
msgstr ""

#: barbican/plugin/dogtag.py:869
msgid "No profile_id specified"
msgstr ""

#: barbican/plugin/dogtag.py:928
msgid "No request returned in enrollment_results"
msgstr ""

#: barbican/plugin/dogtag.py:991
msgid "request_id {req_id} returns COMPLETE but no cert returned"
msgstr ""

#: barbican/plugin/dogtag.py:1003
msgid "Invalid request_status {status} for request_id {request_id}"
msgstr ""

#: barbican/plugin/dogtag.py:1036
msgid "Modify request: unable to cancel: {message}"
msgstr ""

#: barbican/plugin/dogtag.py:1067
msgid "no request found for this order"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:48
msgid "Username for authenticating with KMIP server"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:52
msgid "Password for authenticating with KMIP server"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:56
msgid "Address of the KMIP server"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:60
msgid "Port for the KMIP server"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:64
msgid "SSL version, maps to the module ssl's constants"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:68
msgid "File path to concatenated \"certification authority\" certificates"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:73
msgid "File path to local client certificate"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:77
msgid "File path to local client certificate keyfile"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:81
msgid "Only support PKCS#1 encoding of asymmetric keys"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:254
msgid ""
"An unsupported algorithm {algorithm} was passed to the "
"'generate_symmetric_key' method"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:289
msgid ""
"An unsupported algorithm {algorithm} was passed to the "
"'generate_asymmetric_key' method"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:295
msgid ""
"KMIP plugin does not currently support protecting the private key with a "
"passphrase"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:339
msgid "Secret object type {object_type} is not supported"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:536
msgid "Status: {status}, Reason: {reason}, Message: {message}"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:560
msgid "Bad key file permissions found, expected 400 for path: {file_path}"
msgstr ""

#: barbican/plugin/snakeoil_ca.py:41
msgid "Path to CA certicate file"
msgstr ""

#: barbican/plugin/snakeoil_ca.py:43
msgid "Path to CA certificate key file"
msgstr ""

#: barbican/plugin/snakeoil_ca.py:45
msgid "Path to CA certicate chain file"
msgstr ""

#: barbican/plugin/snakeoil_ca.py:47
msgid "Path to CA chain pkcs7 file"
msgstr ""

#: barbican/plugin/snakeoil_ca.py:50
msgid "Directory in which to store certs/keys for subcas"
msgstr ""

#: barbican/plugin/snakeoil_ca.py:359
msgid "No request_data specified"
msgstr ""

#: barbican/plugin/symantec.py:35
msgid "Symantec username for authentication"
msgstr ""

#: barbican/plugin/symantec.py:37
msgid "Symantec password for authentication"
msgstr ""

#: barbican/plugin/symantec.py:39
msgid "Domain of Symantec API"
msgstr ""

#: barbican/plugin/symantec.py:56
msgid "username is required"
msgstr ""

#: barbican/plugin/symantec.py:59
msgid "password is required"
msgstr ""

#: barbican/plugin/symantec.py:62
msgid "url is required"
msgstr ""

#: barbican/plugin/crypto/crypto.py:27
msgid "Crypto plugin not found."
msgstr ""

#: barbican/plugin/crypto/crypto.py:32
#: barbican/plugin/interface/certificate_manager.py:160
#: barbican/plugin/interface/certificate_manager.py:174
#: barbican/plugin/interface/certificate_manager.py:188
#: barbican/plugin/interface/secret_store.py:129 barbican/tasks/common.py:63
#: barbican/tasks/common.py:64 barbican/tests/tasks/test_common.py:32
#: barbican/tests/tasks/test_common.py:33
msgid "Unknown"
msgstr ""

#: barbican/plugin/crypto/crypto.py:34
msgid "Failed to bind kek metadata for plugin: {name}"
msgstr ""

#: barbican/plugin/crypto/crypto.py:44
msgid "Could not generate private key"
msgstr ""

#: barbican/plugin/crypto/manager.py:37
#: barbican/plugin/interface/certificate_manager.py:50
#: barbican/plugin/interface/secret_store.py:40
msgid "Extension namespace to search for plugins."
msgstr ""

#: barbican/plugin/crypto/manager.py:41
msgid "List of crypto plugins to load."
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:31
msgid "Path to vendor PKCS11 library"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:33
msgid "Password to login to PKCS11 session"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:35
msgid "Master KEK label (used in the HSM)"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:37
msgid "Master KEK length in bytes."
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:39
msgid "HMAC label (used in the HSM)"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:41
msgid "HSM Slot ID"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:61
msgid "library_path is required"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:170
msgid "Feature not implemented for PKCS11"
msgstr ""

#: barbican/plugin/crypto/pkcs11.py:300
msgid "More than one key found for label"
msgstr ""

#: barbican/plugin/crypto/pkcs11.py:304
msgid "General exception"
msgstr ""

#: barbican/plugin/crypto/pkcs11.py:308
msgid "No key handle was found"
msgstr ""

#: barbican/plugin/crypto/pkcs11.py:349
msgid "Apparent RNG self-test failure."
msgstr ""

#: barbican/plugin/crypto/pkcs11.py:386
msgid "HSM returned response code: {hex_value} {code}"
msgstr ""

#: barbican/plugin/crypto/pkcs11.py:413
msgid "Unknown attribute type provided."
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:34
msgid "Key encryption key to be used by Simple Crypto Plugin"
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:50
msgid "KEK not yet created."
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:64
msgid "Unencrypted data must be a byte type, but was {unencrypted_type}"
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:134
msgid "Passphrase not supported for DSA key"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:54
#: barbican/plugin/interface/certificate_manager.py:75
msgid "List of certificate plugins to load."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:71
msgid "Extension namespace to search for eventing plugins."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:120
msgid "Certificate plugin \"{name}\" not found."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:124
msgid "Certificate plugin not found or configured."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:131
msgid "Certificate plugin not found for \"{ca_id}\"."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:140
msgid "Certificate event plugin \"{name}\" not found."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:144
msgid "Certificate event plugin not found."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:152
msgid "Certificate status of {status} not supported"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:162
msgid "Problem seen during certificate processing - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:176
msgid "Problem with data in certificate request - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:190
msgid "Invalid operation requested - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/secret_store.py:44
msgid "List of secret store plugins to load."
msgstr ""

#: barbican/plugin/interface/secret_store.py:55
msgid "No plugin was found that could support your request"
msgstr ""

#: barbican/plugin/interface/secret_store.py:60
msgid "Secret store plugin \"{name}\" not found."
msgstr ""

#: barbican/plugin/interface/secret_store.py:63
msgid "Secret store plugin not found."
msgstr ""

#: barbican/plugin/interface/secret_store.py:69
msgid "Secret store plugin not found for requested operation."
msgstr ""

#: barbican/plugin/interface/secret_store.py:79
msgid "A Content-Type of '{content_type}' for secrets is not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:84
msgid "content-type of '{content_type}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:96
msgid "Secret Content-Encoding of '{content_encoding}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:101
msgid "content-encoding of '{content_encoding}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:110
msgid "No secret information provided to encrypt."
msgstr ""

#: barbican/plugin/interface/secret_store.py:117
msgid ""
"Text-based binary secret payloads must specify a content-encoding of "
"'base64'"
msgstr ""

#: barbican/plugin/interface/secret_store.py:123
msgid "Encoding type must be 'base64' for text-based payloads."
msgstr ""

#: barbican/plugin/interface/secret_store.py:131
msgid "Problem seen during crypto processing - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/secret_store.py:140
#: barbican/plugin/interface/secret_store.py:145
msgid "Problem decoding payload"
msgstr ""

#: barbican/plugin/interface/secret_store.py:153
msgid "Secret Accept of '{accept}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:162
msgid "Not Found. Sorry but your secret is in another castle"
msgstr ""

#: barbican/plugin/interface/secret_store.py:168
msgid "No secret information found"
msgstr ""

#: barbican/plugin/interface/secret_store.py:174
msgid "Requested algorithm is not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:179
msgid "Secret algorithm of '{algorithm}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:189
msgid "No secret store plugins have been configured"
msgstr ""

#: barbican/plugin/interface/secret_store.py:197
msgid ""
"The requested Store Plugin {plugin_name} is not currently available. This"
" is probably a server misconfiguration."
msgstr ""

#: barbican/plugin/util/translations.py:121
msgid "Secret type can not be converted to DER"
msgstr ""

#: barbican/plugin/util/translations.py:133
msgid "Secret type can not be converted to PEM"
msgstr ""

#: barbican/tasks/keystone_consumer.py:36
msgid "Project cleanup via Keystone notifications"
msgstr ""

#: barbican/tasks/resources.py:240
msgid "Process TypeOrder"
msgstr ""

#: barbican/tasks/resources.py:308 barbican/tasks/resources.py:355
msgid "Order type \"{order_type}\" not implemented."
msgstr ""

#: barbican/tasks/resources.py:326
msgid "Update Order"
msgstr ""

#: barbican/tasks/resources.py:374
msgid "Check Certificate Order Status"
msgstr ""

#: barbican/tasks/resources.py:405
msgid "Order type \"{order_type}\" not supported."
msgstr ""

#: barbican/tests/tasks/test_resources.py:214
#: barbican/tests/tasks/test_resources.py:419
msgid "Process TypeOrder failure seen - please contact site administrator."
msgstr ""

#: barbican/tests/tasks/test_resources.py:357
msgid "Update Order failure seen - please contact site administrator."
msgstr ""

